### Send email
POST  http://173.82.235.35:4200/api/v1/mail/send-user-welcome

### Verify email
POST  http://localhost:5000/api/v1/leads/send-mail
content-type: application/json

{
    "email": "biprodas.cse@gmail.com",
    "firstName": "Biprodas",
    "lastName": "Roy",
    "type": "join"
}