import React from 'react'

export default function AboutPage() {
  return (
    <div>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>abouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuut</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>abouttttttttttttttttttttttttttttttttttttttttttttttttttttttt</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
      <h1>about</h1>
    </div>
  )
}
