### Get list of all states
GET http://localhost:5000/api/v1/states

### Get single state
GET http://localhost:5000/api/v1/states/1

### Create a new state
POST  http://localhost:5000/api/v1/states
Content-Type: application/json

{
  "name": "Arizona",
  "countryId": 1
}

### Update a state
PUT  http://localhost:5000/api/v1/states/1
Content-Type: application/json

{
  "name": "Florida"
}

### Delete a state
DELETE  http://localhost:5000/api/v1/states/1